plugins {
    id 'com.android.application'
}

android {
    namespace 'ir.ghadirpartner.nativeapp'
    compileSdk 35

    defaultConfig {
        applicationId 'ir.ghadirpartner.nativeapp'
        minSdk 24
        targetSdk 35
        versionCode 600
        versionName 'R6.0.0'
    }

    buildTypes {
        debug {
            minifyEnabled false
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['/META-INF/{AL2.0,LGPL2.1}']
        }
    }
}
